apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-reverseproxy
  labels:
    app: udagram-reverseproxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-reverseproxy 
  template:
    metadata:
      labels:
        app: udagram-reverseproxy
    spec:
      containers:
      - name: udagram-reverseproxy
        image: docker.io/newthingade/reverseproxy
        imagePullPolicy: Always
        resources:
          requests:
            memory: 64Mi
            cpu: 250m
          limits:
            memory: 1024Mi
            cpu: 500m
        ports:
        - containerPort: 8080
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: udagram-reverseproxy
  labels:
    app: udagram-reverseproxy
spec:
  ports:
  - name: "8080"
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: udagram-reverseproxy
  type: LoadBalancer
